name: shop_smart_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  flutter_iconly: ^1.0.2
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  google_fonts: ^6.3.2
  dynamic_height_grid_view: ^0.0.4
  card_swiper: ^3.0.1
  iconly: ^1.0.1
  ionicons: ^0.2.2
  image_picker: ^1.2.0
  uuid: ^4.5.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.6
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  modal_progress_hud_nsn: ^0.5.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4


flutter_native_splash:
  color: "#2196F3"
  image: assets/images/bag/order_svg.png
  fullscreen: true
  android_12:
    image: assets/images/bag/order_svg.png
    icon_background_color: "#2196F3"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/bag/smart.png"

  min_sdk_android: 21
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/placeholder.png
    - assets/images/bag/
    - assets/images/banners/
    - assets/images/categories/
    - assets/images/profile/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
